import { cn } from '@/lib/utlis'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import { ClerkProvider } from '@clerk/nextjs'
import Provider from '@/components/Providers'

import "react-loading-skeleton/dist/skeleton.css"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>      
      <html lang="en">
        <Provider>
          <body className={cn('min-h-screen font-sans antialiased grainy',inter.className)}>
            <Navbar/>
            {children}
          </body>
        </Provider>
      </html>
    </ClerkProvider>
  )
}
